#!/usr/bin/env php
<?php
/**
 * DeploYii
 *
 * @link https://github.com/giovdk21/deployii
 * @copyright Copyright (c) 2014 Giovanni Derks
 * @license https://github.com/giovdk21/deployii/blob/master/LICENSE
 *
 * Based on the Yii console bootstrap file.
 * http://www.yiiframework.com/
 * Copyright (c) 2008 Yii Software LLC
 * license: http://www.yiiframework.com/license/
 */

define('DEPLOYII_VERSION', '0.5.0');
define('DEPLOYII_STABLE', false); // Whether the current version/release is considered stable or not

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
